"""Type stubs for the compiled search structures (see _hnswlib.cpp)."""

from collections.abc import Callable, Sequence
from typing import Any, Literal

import numpy as np
import numpy.typing as npt

class Index:
    space: str
    dim: int
    num_threads: int
    ef: int
    max_elements: int
    element_count: int
    ef_construction: int
    M: int

    def __init__(self, space: Literal["l2", "ip", "cosine"], dim: int) -> None: ...
    def init_index(
        self,
        max_elements: int,
        M: int = ...,
        ef_construction: int = ...,
        random_seed: int = ...,
        allow_replace_deleted: bool = ...,
    ) -> None: ...
    def reset_index(self) -> None: ...
    def add_items(
        self,
        data: npt.NDArray[Any],
        ids: Sequence[int] | npt.NDArray[Any] | None = ...,
        num_threads: int = ...,
        replace_deleted: bool = ...,
    ) -> None: ...
    def knn_query(
        self,
        data: npt.NDArray[Any],
        k: int = ...,
        num_threads: int = ...,
        filter: Callable[[int], bool] | None = ...,
    ) -> tuple[npt.NDArray[np.uint64], npt.NDArray[np.float32]]: ...
    def get_items(
        self,
        ids: Sequence[int] | npt.NDArray[Any] | None = ...,
        return_type: Literal["numpy", "list"] = ...,
    ) -> Any: ...
    def get_ids_list(self) -> list[int]: ...
    def set_ef(self, ef: int) -> None: ...
    def set_num_threads(self, num_threads: int) -> None: ...
    def index_file_size(self) -> int: ...
    def save_index(self, path_to_index: str) -> None: ...
    def load_index(
        self,
        path_to_index: str,
        max_elements: int = ...,
        allow_replace_deleted: bool = ...,
    ) -> None: ...
    def mark_deleted(self, label: int) -> None: ...
    def unmark_deleted(self, label: int) -> None: ...
    def resize_index(self, new_size: int) -> None: ...
    def get_max_elements(self) -> int: ...
    def get_current_count(self) -> int: ...

class BFIndex:
    space: str
    dim: int
    num_threads: int

    def __init__(self, space: Literal["l2", "ip", "cosine"], dim: int) -> None: ...
    def init_index(self, max_elements: int) -> None: ...
    def reset_index(self) -> None: ...
    def add_items(
        self,
        data: npt.NDArray[Any],
        ids: Sequence[int] | npt.NDArray[Any] | None = ...,
    ) -> None: ...
    def knn_query(
        self,
        data: npt.NDArray[Any],
        k: int = ...,
        num_threads: int = ...,
        filter: Callable[[int], bool] | None = ...,
    ) -> tuple[npt.NDArray[np.uint64], npt.NDArray[np.float32]]: ...
    def get_items(
        self,
        ids: Sequence[int] | npt.NDArray[Any] | None = ...,
        return_type: Literal["numpy", "list"] = ...,
    ) -> Any: ...
    def delete_vector(self, label: int) -> None: ...
    def set_num_threads(self, num_threads: int) -> None: ...
    def save_index(self, path_to_index: str) -> None: ...
    def load_index(self, path_to_index: str, max_elements: int = ...) -> None: ...
    def get_max_elements(self) -> int: ...
    def get_current_count(self) -> int: ...
